<?php

namespace Chep6915\ISocial\Facades;

use Illuminate\Support\Facades\Facade;

class ISocial extends Facade
{
    protected static function getFacadeAccessor()
    {
        return 'ISocial';
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
    }
}